sudo: required
dist: trusty

install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo

script:
  - /snap/bin/hugo
  - cd public
  - git init
  - git add .
  - git -c user.name='travis' -c user.email='travis' commit -m "Deploy for $TRAVIS_COMMIT"
  - git push --force https://
  # Make sure to make the output quiet, or else the API token will leak!
  # This works because the API key can replace your password.
  - git push --set-upstream --force --quiet https://sergiusens:$GITHUB_API_KEY@github.com/sergiusens/sergiusens.github.com.git master &2>/dev/null
