sudo: required
dist: trusty

install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo

script:
  - hugo

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd public
    git init
    git add .
    git commit -c user.name='travis' -c user.email='travis' -m  
    git push --force https://
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://sergiusens:$GITHUB_API_KEY@github.com/sergiusens/sergiusens.github.com.git master &2>/dev/null
  fi
